-- Audit Duration Engine -- log BUG-053 (found and fixed this session) and
-- move FEAT-012 to 'verified' given independent production confirmation.
-- Migration: 015_bug053_and_feat012_verified
-- Created: 2026-09-12
-- Author: Claude (dev session, 2026-09-12, fifty-sixth session)
--
-- BUG-053: found by the fifty-fifth session (flagged only, not logged in
-- tracker_items or fixed, per that session's explicit instruction to
-- document only) -- scripts/check-repo-hygiene.sh's check 4 (stale
-- pre-restructure path references) fails on docs/TRACKER_SNAPSHOT.json,
-- which was introduced by FEAT-012 (fifty-fourth session) and never added
-- to KNOWN_EXCEPTIONS, even though it necessarily mirrors the same
-- archived-history text migration 008 already transcribed from
-- BUGLOG.md (and which IS already exempted). Confirmed the diagnosis was
-- correct, fixed with the same one-line pattern as the existing
-- 008_extract_buglog_history.sql exception, and confirmed the whole
-- pipeline clean afterward: check-repo-hygiene.sh 4/4, smoke_test.php
-- 24/24, http_api_test.php 117/117, tsc clean, expo export, make
-- build-deploy 4/4. This was p1 per the fifty-fifth session's own
-- assessment (it blocks every push to main until fixed) -- logged
-- directly as fixed_unverified rather than open, since the fix lands in
-- this same migration's push.
--
-- FEAT-012: the fifty-fourth session built it and left it fixed_unverified
-- pending confirmation of an actual scheduled production run. The
-- fifty-fifth session found independent evidence this had already
-- happened (docs/TRACKER_SNAPSHOT.md/.json in that session's checkout
-- were freshly generated by a real dev-export-snapshot.yml run against
-- tools.macerti.com) but didn't act on it ("not yet formally moved to
-- verified... just noting the evidence here for whoever does" -- this
-- migration is that). This session independently re-confirms the same
-- evidence via its own fresh git pull: docs/TRACKER_SNAPSHOT.md's own
-- generated timestamp is recent and real, produced by the workflow
-- calling the live endpoint, not a local/sandbox run.

INSERT IGNORE INTO tracker_items (
  code, type, title, user_description, technical_description, status,
  priority, dependencies, tests_to_do, comments
) VALUES (
  'BUG-053',
  'bug',
  'check-repo-hygiene.sh stale-path check fails on docs/TRACKER_SNAPSHOT.json, blocking every push to main',
  NULL,
  'check-repo-hygiene.sh''s check 4 (stale pre-restructure path references) greps every tracked non-.md file for old path names (audit-app, audit-mobile, duration-calculator-php, audit-engine). docs/TRACKER_SNAPSHOT.json (introduced by FEAT-012, fifty-fourth session) mirrors tracker_items'' archived BUGLOG.md history (migration 008), which legitimately contains those old names inside historical text -- the exact "explaining history, not treating it as current" case the script''s header already carves out an exception for. The .md sibling is auto-exempt (the script skips all *.md files); the .json file was missed. FIXED fifty-sixth session: added docs/TRACKER_SNAPSHOT.json to KNOWN_EXCEPTIONS in scripts/check-repo-hygiene.sh, same one-line pattern as the existing 008_extract_buglog_history.sql entry.',
  'fixed_unverified',
  'p1',
  'scripts/check-repo-hygiene.sh',
  'Confirmed fresh, fifty-sixth session: scripts/check-repo-hygiene.sh now reports 4/4 PASS locally (was failing on check 4 before the fix). Needs the next real CI run on this push to confirm the same result on GitHub Actions, not just locally.',
  'Fixed fifty-sixth session (2026-09-12), one-line KNOWN_EXCEPTIONS addition, same shape as commit 64a8d42''s prior fix for migration 008. check-repo-hygiene.sh 4/4, smoke_test.php 24/24, http_api_test.php 117/117, tsc clean, expo export, make build-deploy 4/4 all reconfirmed clean afterward. Needs CI to actually run green on this push before calling it verified -- not yet confirmed on GitHub Actions as of this migration.'
);

UPDATE tracker_items
SET
  status = 'verified',
  comments = CONCAT(
    comments,
    ' -- VERIFIED 2026-09-12 (fifty-sixth session): independently re-confirmed the fifty-fifth session''s evidence on a fresh git pull -- docs/TRACKER_SNAPSHOT.md/.json in this checkout carry a real, recent generated timestamp produced by .github/workflows/dev-export-snapshot.yml actually calling the live tools.macerti.com endpoint, not a local/sandbox run. Both one-time production setup steps (dev_export_secret in live config.php, DEV_EXPORT_SECRET repo secret) are confirmed done.'
  )
WHERE code = 'FEAT-012';

INSERT INTO tracker_updates (item_code, done, next)
VALUES (
  'BUG-053',
  'Found by the fifty-fifth session (flagged, not logged or fixed, per that session''s explicit instruction). This session (fifty-sixth): confirmed the diagnosis, added docs/TRACKER_SNAPSHOT.json to check-repo-hygiene.sh''s KNOWN_EXCEPTIONS (same pattern as the existing 008_extract_buglog_history.sql exception), reconfirmed the whole pipeline clean (hygiene 4/4, 24/24 smoke, 117/117 HTTP, tsc, expo export, build-deploy 4/4), and logged this row directly as fixed_unverified since the fix ships in this same push.',
  'Watch this push''s Actions run and confirm check-repo-hygiene.sh (and the rest of the pipeline) actually goes green on GitHub Actions, not just locally, before moving this to verified.'
),
(
  'FEAT-012',
  'Independently re-confirmed (fifty-sixth session) the fifty-fifth session''s production evidence: a fresh git pull''s docs/TRACKER_SNAPSHOT.md/.json carry a real, recent timestamp from an actual dev-export-snapshot.yml run against the live server, not a sandbox test. Moved from fixed_unverified to verified on that basis.',
  NULL
);
