-- Audit Duration Engine -- merge-reconciliation migration: archive the one
-- piece of docs/DEV_STATUS.md content that migrations 018-021 (this
-- session's own log-unification pass) never saw -- a second, independent
-- parallel session's own new entry, appended to docs/DEV_STATUS.md and
-- pushed to origin/main while this session's deletion of that same file
-- was still local and uncommitted-to-origin.
-- Migration: 022_archive_parallel_session_addendum
-- Created: 2026-09-14
-- Author: Claude (dev session, 2026-09-13/14, fifty-eighth session)
--
-- Context: two independent sessions both started from commit 6c94bc2 and
-- both did large, non-overlapping work (this session: log unification --
-- migrations 018-021; the other: DEBT-004 test relocation + DEBT-006 fix +
-- tracker triage -- its own migration 017). Both sessions self-numbered
-- "fifty-seventh" independently; this session renumbers itself
-- "fifty-eighth" on merge since the other session's commit landed on
-- origin first. The only real merge conflict was docs/DEV_STATUS.md
-- itself: deleted by this session (migrations 018-021 already archived
-- its pre-merge content into session_log), modified by the other (it
-- appended its own new dated section, reproduced verbatim below). This
-- migration is what lets that conflict resolve as "keep the deletion"
-- with zero content loss -- the other session's own work is untouched by
-- any of this; its migration 017 and code changes merge in unchanged.

INSERT INTO session_log (session_label, summary, trigger_text, done_text, not_done_text, handoff_text, commit_hash, ci_status) VALUES
  ('2026-09-13 (fifty-seventh session) [parallel session, merge-archived]', 'no version bump — `DEBT-004` relocation done properly; a bug caught and fixed along the way; tracker triage', NULL, '[Archived verbatim 2026-09-14 by migration 022, part of a merge reconciliation: this is the session-log section a second, independent parallel session (also starting from commit 6c94bc2, which it — like the session doing this archiving — called "fifty-seventh") appended to docs/DEV_STATUS.md for its own DEBT-004/DEBT-006 work, pushed to origin/main while this session\'s own log-unification commit (migrations 018-021, deleting docs/DEV_STATUS.md/docs/BUGLOG.md) was still local. Merging required deleting docs/DEV_STATUS.md per this session\'s own already-committed decision, so this one additional row -- the only content that existed in docs/DEV_STATUS.md but was never seen by migrations 018-021\'s own archival pass -- preserves it with zero loss. See that other session\'s own migration 017_debt004_progress_and_triage.sql for the structured/DB-native version of the same work.]

## 2026-09-13 (fifty-seventh session) — no version bump — `DEBT-004` relocation done properly; a bug caught and fixed along the way; tracker triage

**Note on session numbering**: this session started from the same base commit (`66c6273`) as the fifty-fifth/fifty-sixth sessions above, without visibility into each other — both independently self-numbered "fifty-fifth" at first. Renumbered to fifty-seventh (after, not instead of, their fifty-sixth) when reconciling the two pushes; the migration file below is numbered `017` for the same reason (`015`/`016` were already claimed by their session by the time this one\'s work got pushed).

**Trigger**: continuing the standing session workflow after Mahdi confirmed he\'d completed the `dev-export` one-time setup (`dev_export_secret` in the live `config.php`, `DEV_EXPORT_SECRET` GitHub Actions secret). `git pull` on session start showed nothing new, and `docs/TRACKER_SNAPSHOT.md` still didn\'t exist — checked the workflow\'s run history via the GitHub API directly (`GET .../actions/workflows/dev-export-snapshot.yml/runs`) and found **zero runs ever**, not a failure, just the 6-hour schedule not having fired yet. Manually dispatched it (`POST .../dispatches`) to test the full pipeline immediately rather than waiting — run `34714140136` completed with `conclusion: success` within about 15 seconds. `git pull` afterward brought in `docs/TRACKER_SNAPSHOT.json`/`.md` for the first time, containing real production data.

**This mattered beyond just testing infrastructure**: reading that file answered Mahdi\'s own multi-session-old question about whether his live edits actually worked. They did — `BUG-051`, `BUG-052`, and `DEBT-001` all show `closed` in the real tracker (he tested and closed them himself), and there are zero open bugs left. Two annotations were sitting untriaged: `ANN-006` (verbatim the same complaint already fully captured in `DEBT-002`\'s own technical description — a duplicate never marked closed when that triage happened) and `ANN-008` (genuinely new: "for each annotation you show the x and y position ... it would also be good if you give more details regarding the element the user pointed at like its name its container or technical designation").

### `DEBT-004` — the tests/ relocation half, done properly

Before touching anything: grepped `REPOSITORY_ARCHITECTURE.md` and found its own status note explicitly says the tests/ relocation was **evaluated and deliberately deferred** by the **ninth session** — "relative-`require` coupling made this the lower-risk call per the spec\'s own \'where practical\' wording." `DEBT-004` itself (opened sessions thirty-six through thirty-nine, then carried untouched across many more) never cross-referenced that decision anywhere in its own tracker text — it was re-flagged as plain oversight when it had actually been a considered, reasoned call. Worth naming plainly: this is exactly the kind of cross-session context loss the tracker system and now `docs/TRACKER_SNAPSHOT.md` exist to prevent, and it happened anyway, in this same project, on this exact item.

Investigated the *actual* coupling before deciding whether to proceed: `grep`\'d for `require`/`__DIR__` across both test files. Only `smoke_test.php` has any relative-path coupling at all — 9 lines, all pointing into `src/backend/{data,engine}/`. `http_api_test.php` is a pure HTTP client with zero filesystem coupling. This is meaningfully narrower than the ninth session\'s context (a simultaneous, much larger multi-tree architecture migration), which is presumably why "lower-risk" made sense there but doesn\'t necessarily still apply to this one narrow, standalone move today.

**What shipped**: `git mv src/backend/tests tests/backend` (history preserved). `smoke_test.php`\'s 9 requires fixed. `Makefile` updated (`test`, `test-http`, `build-deploy` targets — the two `cd src/backend && ...` invocations simplified to plain repo-root-relative calls, since neither test file needs a specific working directory once paths are fixed). `.github/workflows/build-test-publish.yml` updated (3 steps — 2 test-invocation steps had their now-unnecessary `working-directory: src/backend` removed entirely, 1 artifact-assembly `cp` line updated). `check-repo-hygiene.sh`\'s stale-pre-restructure-path pattern extended to include the old `src/backend/tests` path, so any future reintroduction of it gets caught automatically — required adding three narrow, well-commented exceptions for genuinely historical text (two migrations\' own stored tracker-item prose, plus the auto-generated `docs/TRACKER_SNAPSHOT.json`, which will self-resolve on its next refresh).

### A real bug, introduced and caught within this same session

The first fix gave `smoke_test.php` a single hardcoded relative path (`__DIR__ . \'/../../src/backend/data/...\'`) — correct for running the file from its new repo location, but **wrong** for the *other* real place this exact file lives: copied verbatim into `_deploy/tests/` by the same `build-deploy` Makefile target, unchanged by this session. In the deploy artifact, `data/`/`engine/` are flat siblings of `tests/` one level up, not two levels up through a `src/backend/` that doesn\'t exist there at all.

`make build-deploy` → `check-deploy-artifact.sh` reported a clean pass — **a false pass**. Traced why: the checker\'s require-resolution logic (`realpath -m` then `[ -f "$resolved" ]`) only checks that *something* exists at the resolved path, never that the resolved path stays *inside* the artifact directory. Run from inside this full repo checkout, `_deploy/tests/../../src/backend/data/parameters.php` resolves by climbing straight back out of `_deploy/` into the real `src/backend/` sitting right next to it — which is a real file, so the check passed, while telling us nothing about whether a genuinely isolated deployment would work.

Confirmed the gap concretely: copied `_deploy/` to `/tmp/isolated_deploy_test/` (nothing else in that directory at all) and ran `php tests/smoke_test.php` from there directly — `PHP Fatal error: ... Failed opening required \'/tmp/isolated_deploy_test/tests/../../src/backend/data/parameters.php\'`. Exactly the failure mode a real production deployment would hit.

**Fixed properly**: `smoke_test.php` now resolves `$backendRoot` at runtime — `is_dir(__DIR__ . \'/../../src/backend\') ? __DIR__ . \'/../../src/backend\' : __DIR__ . \'/..\'` — then requires everything relative to that. Verified in both directions by the same true-isolation method: repo context (`php tests/backend/smoke_test.php` from the repo root, 24/24) and a fresh isolated copy of the rebuilt artifact (24/24) — not just trusting the automated checker, which had just been shown to have a blind spot for exactly this.

### `DEBT-006` (new, found and fixed same session): hardened `check-deploy-artifact.sh` itself

Logged the checker\'s own gap as its own tracker item rather than silently patching around it. Fix: after `realpath -m` resolves a required path, also assert it starts with the artifact directory\'s own `realpath` — anything that resolves to a real file **outside** the artifact now fails loudly (`ESCAPING_REQUIRES`), distinct from the existing "resolves to nothing" (`MISSING_REQUIRES`) case. Verified two ways: the real, now-fixed artifact still passes cleanly (positive test), and a scratch copy with the exact original broken pattern reintroduced correctly fails (negative test) — confirming the hardened check actually catches this class of bug rather than just happening to pass by coincidence again.

Also documented, in the checker\'s own comments, a real remaining limitation rather than leaving it silent: `smoke_test.php`\'s requires now go through a runtime `$backendRoot` variable, not a literal `__DIR__ . \'...\'` string, so the checker\'s regex-based scan (which specifically greps for that literal pattern) doesn\'t see them at all — not a false pass, just a blind spot for this one deliberately-dynamic file. Judged not worth engineering the static check to understand PHP runtime branches for one file; the true-isolation manual test already performed is a *stronger* verification for this specific file than the automated check provides for anything else anyway (it actually executes the code, rather than only proving a path resolves to some file).

### Tracker triage

- **`ANN-006`** closed as a duplicate of `DEBT-002` — identical raw complaint text, already fully captured there with a real remediation plan, just never marked closed when that triage originally happened.
- **`ANN-008`** ("give more details about the pointed-at element, not just x/y") triaged into **`FEAT-013`**, scoped specifically to *not* require `DEBT-003`\'s full app-wide `testID` rollout first: a fallback that captures tag name / `aria-label` / nearest recognizable-ancestor text when no `testID` is present, which is the common case today per `DEBT-003`\'s own finding (zero `testID` coverage app-wide before `BUG-050`\'s opportunistic additions). Logged `open`/`p2`, behind the P1 queue — not built this session.
- **`FEAT-012`** marked `verified` — the real production dispatch run above is the actual verification event, and per this project\'s own established distinction (`fixed_unverified` vs. `verified`), a confirmed real production run is a stronger signal than this sandbox\'s local testing was able to provide for a backend-only item.

### Two rounds of test-assertion fallout, both legitimate, neither a real regression

1. Adding `DEBT-006`/`FEAT-013` via migration pushed seeded `tracker_items` from 66 to 68 — the same two hard-coded count assertions from the previous session\'s own churn (64→66) needed the same treatment again (66→68). Comment strings updated to explain the running total\'s provenance rather than just the bare number.
2. `FEAT-012`\'s own `comments` field (written this session) legitimately mentions "`BUG-051`/`052`/`DEBT-001` closed" in prose — which a case-insensitive substring search for `BUG-051` correctly also matches now, alongside `BUG-051` itself. The old test asserted *exactly* one result; loosened to "at least one result, `BUG-051` included" instead, since asserting an exact global count against a tracker whose whole design encourages cross-referencing text between items was always going to keep breaking as that text accumulates — this isn\'t a one-off fix so much as a more correctly-scoped assertion going forward.

### A third issue, worth its own note: this session\'s migration first draft looked like a SQL bug but wasn\'t

First attempt at this session\'s own tracker migration (numbered `015` at the time it was written, before the fifty-fifth/fifty-sixth sessions\' own `015`/`016` were discovered already pushed and this one renumbered to `017` — see the note at the top of this entry) failed with a foreign-key violation on the final `INSERT INTO tracker_updates` statement. Spent real effort ruling out a SQL-escaping bug first — checked every apostrophe in the file for correct `\'\'`-doubling, ran the file directly through the `mysql` CLI (which parses multi-statement files with a real, correct SQL parser, unlike `db/Migrations.php`\'s own deliberately-simplified custom splitter) to get MySQL\'s own precise error location rather than PDO\'s wrapped one, and confirmed the SQL itself was syntactically 100% valid — the CLI reached the very last statement in the file before failing. The actual cause: `ANN-006`/`ANN-008` are **real, production-only rows** (created live by Mahdi in the app, never part of any migration\'s seed data), so they don\'t exist in a fresh local/CI database at all. The `UPDATE ... WHERE code = \'ANN-006\'` statements are correctly no-ops in that case (0 rows affected is not an error) — but a plain `INSERT INTO tracker_updates (item_code, ...) VALUES (\'ANN-006\', ...)` immediately afterward then violates the foreign key, since the parent row genuinely doesn\'t exist in this environment. **Fixed** by switching those six `tracker_updates` inserts from `INSERT ... VALUES` to `INSERT ... SELECT ... WHERE EXISTS (SELECT 1 FROM tracker_items WHERE code = \'...\')` — safe and correct in both a fresh local/CI database (silently inserts nothing for the two codes that don\'t exist there) and the real production database (inserts normally, since both codes are genuinely present there).

### Reconciling with a parallel session

Pushing this session\'s work hit a non-fast-forward rejection: a different dev session had been working on this same repo concurrently, starting from the same base commit (`66c6273`), without either session visible to the other. That session found and fixed its own real bug (`BUG-053` — `check-repo-hygiene.sh` failing on `docs/TRACKER_SNAPSHOT.json`, then a second self-inflicted round when their own fix migration\'s explanatory text self-triggered the same check) and pushed two migrations (`015_bug053_and_feat012_verified.sql`, `016_fifty_sixth_session_log.sql`) plus their own `DEV_STATUS.md`/`CHANGELOG.md`/test-count updates, all before this session\'s push landed.

Both sessions had independently claimed migration number `015` for different files, and both self-numbered their first entry "fifty-fifth session" — an inherent risk of two sessions starting from the same point with no coordination. Resolved by treating their push as authoritative for the numbers already claimed: this session\'s migration renumbered `015` → `017`, this session\'s own label renumbered "fifty-fifth" → "fifty-seventh" (after, not instead of, their fifty-fifth/fifty-sixth). Also fixed this session\'s own `FEAT-012` update to `CONCAT` onto `comments` rather than replace it outright — both sessions had independently verified the same real thing (the live production dev-export run) via different evidence, and a straight replace would have silently discarded whichever one applied first, depending on migration file sort order. Confirmed after merging: both notes survive, in order, in the real row.

Reconciled `check-repo-hygiene.sh` (union of both sessions\' `KNOWN_EXCEPTIONS`, kept this session\'s `STALE_PATTERN` addition for `src/backend/tests`, added an exception for both migration files that self-reference old paths in their own prose — theirs and this session\'s renumbered one), and `tests/backend/http_api_test.php` (recalculated the genuinely combined tracker_items count as **69**, not either session\'s own number in isolation — 66 base + 1 from their `BUG-053` + 2 from this session\'s `DEBT-006`/`FEAT-013`). `docs/DEV_STATUS.md` and `CHANGELOG.md` merged by keeping both sessions\' entries in full, in chronological order, rather than either session\'s account overwriting the other\'s.



`migrate.php` **15/15** on this session\'s own work before reconciling with the parallel fifty-fifth/fifty-sixth sessions\' push (confirmed idempotent, `0 new, 15 skipped` on a second run). After reconciling both pushes together (see "Reconciling with a parallel session" below): **17/17** migrations (14 original + this session\'s own 2-row addition, now renumbered `017` + the fifty-fifth/fifty-sixth sessions\' `015`/`016`), tracker_items **69** total (66 base + 1 `BUG-053` + 2 `DEBT-006`/`FEAT-013`), confirmed idempotent again (`0 new, 17 skipped`). `seed.php` OK. `smoke_test.php` **24/24** (both from the repo path directly and via `make test`). `http_api_test.php` **117/117** after all rounds of test-assertion fixes — this session\'s own (moving the tests: 116/117 first, the search-by-code assertion) plus reconciling the fifty-fifth/fifty-sixth sessions\' own count changes to the same file (66→67→69 for the total, 52→53 unchanged since neither `DEBT-006` nor `FEAT-013` is `type=\'bug\'`). `check-repo-hygiene.sh` **4/4** (including this session\'s three exceptions plus the fifty-sixth session\'s own `BUG-053`-migration exception, merged together). `make build-deploy` + `check-deploy-artifact.sh` **4/4** — with the hardened checker. Plus the true-isolation run of the rebuilt artifact\'s own `smoke_test.php` (**24/24**), re-run one final time after the merge to make sure nothing had drifted.

### NOT DONE

- **`DEBT-004`\'s frontend-unit-test half**: still fully open. Choosing Jest vs. Vitest and scoping an initial coverage target (wizard calculation state/hooks) is real, separate work — not attempted this session, which went entirely to the relocation half plus the bug it surfaced.
- **`FEAT-013`**: logged and scoped, not built. Small, self-contained, no dependency on anything else in the open queue.
- **Everything else in the P1 queue** (`DEBT-002`, `FEAT-001`, `FEAT-008` slice 2, `FEAT-009`) — untouched. This session\'s chunk was entirely "finish a long-overdue debt item properly, including a bug it introduced along the way, plus clear a small tracker-hygiene backlog" — a deliberate, different kind of contribution than another feature slice, in the same spirit as the fifty-fourth session\'s bug-and-tooling-focused chunk.

### Hand-off for the next developer

1. **By priority, unchanged**: `DEBT-002` (AdminRoles redesign — part 1, the low-risk `maxWidth` bump, is genuinely quick and independent of part 2\'s design decision), `FEAT-001`, `FEAT-008` slice 2, `FEAT-009`, then `DEBT-004`\'s remaining frontend-unit-test half and `FEAT-013`.
2. **Before touching any item flagged as long-carried-over "obvious" debt**: check whether an earlier session already deliberately evaluated and deferred it for a real reason, the way the ninth session had for `DEBT-004`, before assuming it\'s pure oversight. `docs/TRACKER_SNAPSHOT.md` and this file are both worth a search for the item\'s code before starting, not just its own `tracker_items` row — the reasoning that matters may be attached to a *different* item or an architecture doc, not the one being worked.
3. **A pattern worth carrying forward generally**: this session\'s actual bug (the escaping relative path) was caught by manually testing in true isolation, not by trusting an automated check that reported success. Worth treating "the checker passed" as necessary but not sufficient for anything touching file-system layout or deployment structure specifically — a check written and run inside a full checkout can have blind spots a real isolated environment doesn\'t share, as this session\'s own `check-deploy-artifact.sh` gap demonstrated directly.
4. **Two smaller open items from the parallel session\'s own queue, for completeness**: `BUG-053` sits at `fixed_unverified` (their fix, confirmed green on CI per their own account — a live click-through/CI-watch would close it out). `DEBT-005` (from the fifty-fourth session, still open) needs a real decision on `BUGLOG.md`\'s status, not more investigation — worth asking Mahdi directly given how long `BUG-051`/`052` sat on exactly that kind of unresolved decision before.

**Push**: `Makefile`, `.github/workflows/build-test-publish.yml`, `scripts/check-repo-hygiene.sh`, `scripts/check-deploy-artifact.sh`, `tests/backend/` (moved from `src/backend/tests/`, `smoke_test.php` fixed, `http_api_test.php`\'s count + search assertions fixed, plus reconciled against the fifty-fifth/fifty-sixth sessions\' own count changes to the same file), `src/backend/db/migrations/017_debt004_progress_and_triage.sql` (new — renumbered from this session\'s original `015` once the fifty-fifth/fifty-sixth sessions\' `015`/`016` were discovered already pushed), `CHANGELOG.md`, and this entry.', NULL, NULL, NULL, NULL);
